### ISSUE TITLE
RUSTSEC-2021-0019 - Multiple soundness issues, maintenance status

### ISSUE THREAD

**Issue by martin-t** [rust-x-bindings/rust-xcb#107]
There's an [advisory](https://rustsec.org/advisories/RUSTSEC-2021-0019.html) out for XCB. The individual issues appear to be reported here but i don't see any response from you on any of them:
- https://github.com/rtbo/rust-xcb/issues/78
- https://github.com/rtbo/rust-xcb/issues/94
- https://github.com/rtbo/rust-xcb/issues/95
- https://github.com/rtbo/rust-xcb/issues/96

The [issue with details](https://github.com/RustSec/advisory-db/issues/653) also says XCB is unmaintained but i can see commits on a branch from a week ago. Are you still maintaining this crate? If so, would you, please, look at those issues? XCB is (transitively) a dependency of a lot of crates such as egui, conrod, alacritty and rg3d, though i don't know how many use the relevant functions.

I understand maintaining a popular crate is a lot of work and often not even interesting work. Would you be open to spreading the responsibility around a little? Perhaps you could create a Github organization with maintainers of some of these big crates as members if they would be interested. I also usually suggest using [Rust Bus](https://users.rust-lang.org/t/bus-factor-1-for-crates/17046).

Finally, since this is a security issue, would you pin it so it receives more attention?

---

Edit(2021-11-07): One more [advisory](https://rustsec.org/advisories/RUSTSEC-2020-0097):
- https://github.com/rtbo/rust-xcb/issues/93
This is actually older but our CI only picked it up recently fsr. Adding it here so it's all in one place.

**Comment by rtbo** [comment]
`rust-xcb` is now part of the new organization `rust-x-bindings`.
I plan to move there also `toy_xcb` and `xkbcommon-rs`

**Comment by rtbo** [comment]
`v1.0.0-beta.0` is released to [crates.io](https://crates.io/crates/xcb/1.0.0-beta.0). See branch [v1.0-dev](https://github.com/rust-x-bindings/rust-xcb/tree/v1.0-dev).
Any comment in the new API, please don't hesitate to voice. Either in this issue or in another one.
You can get a good grasp on the new API from the [ReadMe](https://github.com/rust-x-bindings/rust-xcb/blob/v1.0-dev/README.md) (in the v1.0-dev branch), from the [examples](https://github.com/rust-x-bindings/rust-xcb/tree/v1.0-dev/examples), and from the [documentation](https://rust-x-bindings.github.io/rust-xcb/branches/v1.0-dev/xcb/).

**Comment by rtbo** [comment]
[v1.0.0](https://crates.io/crates/xcb/1.0.0) is released.
