### ISSUE TITLE
*Event fields having mask type in accessor function have generic type in new() argument

### ISSUE THREAD

**Issue by xkr47** [rust-x-bindings/rust-xcb#145]
(in v1.0-dev branch)

Examples:
1. ConfigureRequestEvent: https://rust-x-bindings.github.io/rust-xcb/branches/v1.0-dev/xcb/x/struct.ConfigureRequestEvent.html
    * `value_mask` parameter is `u16` in `new()` but `ConfigWindowMask` in `value_mask()`
2. KeyPressEvent https://rust-x-bindings.github.io/rust-xcb/branches/v1.0-dev/xcb/x/struct.KeyPressEvent.html
    * `state` parameter is `u16` in `new()` but `KeyButMask` in `state()`

Is this deliberatre or accidental?

**Comment by rtbo** [comment]
Hi,
Thanks for reporting, no it is not deliberate

**Comment by rtbo** [comment]
Now fixed.
