### ISSUE TITLE
`xcb_get_image` and supporting constants missing since v1.0

### ISSUE THREAD

**Issue by vodik** [rust-x-bindings/rust-xcb#174]
I made a simple screenshot tool, which uses `xcb_get_image` and a few supporting constants. These all seem to have been dropped in the v1.0 update:
```rust
    let cookie = xcb::get_image(
        &conn,
        xcb::IMAGE_FORMAT_Z_PIXMAP as _,
        screen.root(),
        0,
        0,
        width,
        height,
        u32::MAX,
    );
```
Are there any plans to restore this functionality? And if so, would you be interested in a screenshot example utility? It would mean a dev dependency on a png crate.

**Comment by vodik** [comment]
Oh damn, I missed that. I also didn't think to check the updated examples. Sorry and thanks!

That said, is there any interest in adding an example that saves a screenshot? I got everything working again, I can contribute it you'd like.

**Comment by rtbo** [comment]
Sure, more examples are welcome!
