### ISSUE TITLE
screensaver protocol errors aren't handled

### ISSUE THREAD

**Issue by kelnos** [rust-x-bindings/rust-xcb#177]
I tried to enable the screensaver extension when connecting to the X server, but then later, when I did something bad (I was improperly enumerating connected monitors using xrandr, and then creating a window on each monitor), I got:
```
thread 'main' panicked at 'internal error: entered unreachable code: Could not match extension event', /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-1.1.1/src/error.rs:301:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::unreachable_display
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:64:5
   3: xcb::error::resolve_error
             at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-1.1.1/src/error.rs:301:17
   4: xcb::base::Connection::check_request
             at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-1.1.1/src/base.rs:1478:27
   5: bscreensaver::create_blanker_windows
             at ./src/lib.rs:82:9
   6: bscreensaver::main
             at ./src/main.rs:45:31
   7: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
```

I added a `println!()` before the `unreachable!()`, and it was telling me `ScreenSaver` for `emitted_by`.  However, this is odd, because the spec for the extension says it defines no errors.

This isn't a showstopper (as I've fixed the code that was doing something bad), but it _is_ curious.  Not sure what to do here, if anything.

**Comment by rtbo** [comment]
`emitted_by` is supposed to be the name of a request, not the name of the extension. 
If you have activated the extensions you are using in the `Connection` constructor, the `unreachable` section should never be reached. Otherwise it is a bug that I have to fix.
Do you have code to reproduce?

**Comment by kelnos** [comment]
Sure, looks like the reproducer was pretty easy: https://github.com/kelnos/xcb-panic-reproducer

If you remove the `xcb::Extension::ScreenSaver` from the `connect_with_extensions()` call, it exits with a regular protocol error (as it should, as a 0x0 window is invalid).  With the screensaver extension requested, it instead panics.

**Comment by rtbo** [comment]
Thanks, indeed there was a bug. The code now correctly resolves the protocol error (which has nothing to do with Screensaver).
