### ISSUE TITLE
[Question] How to check for WM_DELETE_WINDOW?

### ISSUE THREAD

**Issue by acheronfail** [rust-x-bindings/rust-xcb#178]
I'm trying to kill a window gracefully with `xcb`, but I'm not sure how to do it with this lib. :thinking: 

For reference, I'd like to perform steps very similar to this: https://github.com/i3/i3/blob/dba30fc9879b42e6b89773c81e1067daa2bb6e23/src/x.c#L326-L356

Which is basically:

* Check if a window has declared that it supports `WM_DELETE_WINDOW`
* If it has support, then send `WM_DELETE` to the client
* If it doesn't have support, then send `x::KillClient`

The last point is relatively straightforward:

```rs
self.conn.send_and_check_request(&x::KillClient { resource: window.resource_id() })?;
```

But, for the life of my I haven't figured out a way to check `WM_DELETE_WINDOW` or send the `WM_DELETE` request with this lib.
Any pointers would be greatly appreciated!

**Comment by rtbo** [comment]
Hi,
To check if window supports a protocol, you can use `GetProperty` request as follow:
```rust
let cookie = conn.send_request(&x::GetProperty {
    delete: false,
    window,
    property: atoms.wm_protocols,
    r#type: x::ATOM_ATOM,
    long_offset: 0,
    long_length: u32::MAX,
});

let reply = conn.wait_for_reply(cookie)?;
let supports_wm_delete_window = reply.value::<x::Atom>().contains(&atoms.wm_del_window);
```
The protocol is reported only if it was previously activated (using `ChangeProperty`, check [basic_window.rs](https://github.com/rust-x-bindings/rust-xcb/blob/main/examples/basic_window.rs)).
To send `WM_DELETE_WINDOW` to the client, use `SendEvent`:
```rust
let data = x::ClientMessageData::Data32([
    atoms.wm_del_window.resource_id(),
    x::CURRENT_TIME,
    0,
    0,
    0,
]);

let event = x::ClientMessageEvent::new(window, atoms.wm_protocols, data);

conn.send_request(&x::SendEvent {
    propagate: false,
    destination: x::SendEventDest::Window(window),
    event_mask: x::EventMask::NO_EVENT,
    event: &event,
});

conn.flush()?;
```
