### ISSUE TITLE
`width` and `height` of `xcb::xfixes::GetCursorImageReply` are private

### ISSUE THREAD

**Issue by RealKC** [rust-x-bindings/rust-xcb#186]
Also applies to `xcb::xfixes::GetCursorImageAndNameReply`

**Comment by RealKC** [comment]
I've written a hacky fix that's referenced above, is there a better way or should I open a PR with that fix?

**Comment by rtbo** [comment]
Hi, your hack looks good to me. There's often not much but to introduce hard-coded exceptions.
