### ISSUE TITLE
Contributions: how to contribute documentation?

### ISSUE THREAD

**Issue by Antikyth** [rust-x-bindings/rust-xcb#198]
Hello! I'm using `rust-xcb` in the development of a window manager I've been working on, and I have found the documentation to be kinda lacking in quite a few areas that I have been using. Is it possible to contribute documentation to `rust-xcb`, and, if so, how can I do that?

From taking a quick look at previous commits made to this repository, it looks like editing `xml/xproto.xml` is how that can be achieved, but I'm not sure how much documentation might be accepted into `rust-xcb`, and I'm not completely sure of all the steps that I should take when editing the xml files (e.g. could I be breaking things?).

I can most likely provide a large amount of in-depth documentation, from the basic descriptions to explanations, examples, recommendations, etc.. I will probably be using `rust-xcb` a lot over the next few months, and I am hoping that my project will have others contributing to it as well, so good documentation is pretty valuable to me. I'm more than willing to do as much documentation as I can, I actually enjoy it quite a lot! Let me know if this is something I could help with.

By the way, I hope this is the correct place to ask this question - I didn't see another kind of discussions/contact area around here.

**Comment by rtbo** [comment]
Hi, indeed the easiest is to edit directly the `xproto.xml` file (and other xml files for extensions). Such effort is very welcome!

You should not be afraid of break anything. The continuous integration scripts include checking that the documentation is correctly generated. If you mimic the xml tags of the little documentation already existing you should not have too much surprises.

Also if you see that the generated doc is not as good as it should, you can improve the code in [build/cg/doc.rs](https://github.com/rust-x-bindings/rust-xcb/blob/main/build/cg/doc.rs)
