### ISSUE TITLE
Access xcb_visualtype_t

### ISSUE THREAD

**Issue by vikigenius** [rust-x-bindings/rust-xcb#200]
Cairo `XCBVisualType` needs `pub unsafe fn from_raw_none(ptr: *mut ffi::xcb_visualtype_t) -> XCBVisualType`

Previously this library had the following as the `VisualType` definition

```rust
pub struct Visualtype {
    pub base: xcb_visualtype_t,
}
```

So I could just get the base and unsafe cast

```rust
unsafe {
    cairo::XCBVisualType::from_raw_none(
        visual_type.base as *mut xcb::ffi::xcb_visualtype_t as *mut cairo_sys::xcb_visualtype_t,
    )
}
```

But now the definition of VisualType is

```rust
#[derive(Copy, Clone)]
pub struct Visualtype {
    data: [u8; 24],
}
```

How do I get a `cairo::XCBVisualType` now ?

**Comment by rtbo** [comment]
The layout in the `data` field of `Visualtype` is compatible with the C layout, so you should be able to cast a pointer or reference to `Visualtype` to a pointer of `cairo::sys::xcb_visualtype_t`.
Please let me know if that works.

**Comment by vikigenius** [comment]
Oh thanks a lot, that does seem to work, here is what I ended up with

```rust
unsafe {
    cairo::XCBVisualType::from_raw_none(
        visual_type as *mut xcb::x::VisualType as *mut cairo_sys::xcb_visualtype_t,
    )
}
```
