### ISSUE TITLE
Implement AsRef for Connection ?

### ISSUE THREAD

**Issue by vikigenius** [rust-x-bindings/rust-xcb#201]
Thanks for the wonderful crate.

I feel like it's a good idea to implement AsRef for Connection. Because it is a common pattern to extend xcb in other crates using a wrapper type for example ewmh implementations like `xcb-wm`.

And implementing AsRef would make it easier to write generic code w.r.t these wrapper connections.

This should be pretty easy and I can contribute a PR if you want.

**Comment by rtbo** [comment]
If it helps using `rust-xcb` in other crates, sure I'm open to it.
I don't see what `AsRef` will bring. Do you intend to convert to a FFI pointer or ref?

**Comment by vikigenius** [comment]
@rtbo 

The idea is if I have a wrapper type that wraps connection like

```rust
pub struct EwmhConnection {
    pub conn: xcb::Connection,
    // Other fields
}
```

Then I can implement generic functions that take either a reference to either `EwmhConnection` or `xcb::Connection` by implementing

```rust
impl AsRef<xcb::Connection> for EwmhConnection {
    fn as_ref(&self) -> &xcb::Connection {
        &self.conn
    }
}
```

**Comment by rtbo** [comment]
I see, but this implementation should be in the `xcb-wm` crate. 
Is there anything that should be in the `xcb` crate?

**Comment by vikigenius** [comment]
@rtbo Yes the code that I provided should be in the `xcb-wm` crate. But it won't work unless you implement

```rust
impl AsRef<Connection> for Connection {
    fn as_ref(&self) -> &Connection {
        self
    }
}
```

And this part should be in the `xcb` crate because of the orphan rule iirc.
