### ISSUE TITLE
Are all the atoms interned automatically?

### ISSUE THREAD

**Issue by vikigenius** [rust-x-bindings/rust-xcb#203]
I am trying to get a better understanding of this amazing crate, and I am very interested in how you are doing code gen. 

So I hope you don't mind answering my questions.

Looking at https://github.com/rust-x-bindings/rust-xcb/blob/777edbdbb36d113ca4f3cb5611a40975f272a433/xml/xproto.xml#L889

It seems like you have an xml file that specifies a bunch of atoms. And they are generated as Rust constants during [build](https://docs.rs/xcb/latest/src/xcb/opt/rustwide/target/x86_64-unknown-linux-gnu/debug/build/xcb-5252da9e4620ab2c/out/xproto.rs.html#7780)? 

My question is are these atoms being automatically interned somewhere when a new connection is created?

Also just to get more clarity, is there any advantage to using this setup? Was the XML handwritten? If so won't it be the same effort to write the equivalent Rust code for this instance?

**Comment by rtbo** [comment]
The XML files are from the upstream C XCB project which generate the C code from XML.
What I do is that I use them to generate the rust code with my own build code.
The atoms defined in the XML files are defined as rust constants. See https://rust-x-bindings.github.io/rust-xcb/xcb/x/index.html#constants.
As far as I know these are pre-defined atoms recognized by the X server, there is no need to intern them.

I think the XCB folks handwritten the XML by hand to describe the X protocol. There is a big advantage to the XML description: it allows to generate the other languages bindings as well.
Wayland works in exactly the same way.
