### ISSUE TITLE
x::Atom::none() should be made const fn

### ISSUE THREAD

**Issue by ratijas** [rust-x-bindings/rust-xcb#210]
Use case: I wanted to initialize a global (static) variable with a "none" atom.

**Comment by rtbo** [comment]
Not possible at the moment. `Atom::none()` is a trait implementation.
```rust
impl base::Xid for Atom {
    const fn none() -> Self { Atom { res_id: 0 } }
    fn resource_id(&self) -> u32 { self.res_id }
}
```
```
error[E0379]: functions in traits cannot be declared const
    --> /home/remi/dev/rust-xcb/target/debug/build/xcb-a03be5dd4e5ee2d0/out/xproto.rs:5310:5
     |
5310 |     const fn none() -> Self { Atom { res_id: 0 } }
     |     ^^^^^ functions in traits cannot be const
```

See https://github.com/rust-lang/rust/issues/71971 for tracking.
There is also the [`const_trait_impl` feature](https://github.com/rust-lang/rust/issues/67792) which could help.
Don't hesitate to reopen when this becomes stable.

**Comment by ratijas** [comment]
Is it needed as a trait method? Can every struct/type have a const version of `none()` which is not a subject to trait method restrictions? Practical code (an app, not a library) dealing with X11 stuff probably won't need that extra level of abstractions anyway.

**Comment by ratijas** [comment]
In fact, I checked out the repo locally, grepped, and haven't found any single trait-usage of `none()`. But there are, like, only two total.

**Comment by rtbo** [comment]
> Is it needed as a trait method?

I'd say no, but I can't change this without breaking semver. I'd need to make a version 2.

I forgot to mention that you can use [x::ATOM_NONE](https://rust-x-bindings.github.io/rust-xcb/xcb/x/constant.ATOM_NONE.html) for static initialization.
