### ISSUE TITLE
Interest in a shared crate for getting a raw pointer to an xcb_connection_t?

### ISSUE THREAD

**Issue by psychon** [rust-x-bindings/rust-xcb#217]
Hi there,

I recently got https://github.com/psychon/x11rb/issues/782 and wanted to use xkbcommon with x11rb's XCBConnection. Let's look at some of the available crates:

- xkbcommon: expects an [`xcb::Connection`](https://github.com/rust-x-bindings/xkbcommon-rs/blob/cc4b25ac3fb157d37d35eb49ac59f31c71ad52cf/src/xkb/x11/mod.rs#L42-L43)
- xkbcommon-dl has [`pub type xcb_connection_t = c_void;`](https://github.com/francesca64/xkbcommon-dl/blob/8fb3c247662b96f6bfc3552095cbaddddc2aed02/src/x11.rs#L3)
- [xkbcommon-sys](https://github.com/meh/rust-xkbcommon-sys) seems to use bindgen, but its "safe counterpart"...
- ...rust-xkb then depends on [`xcb::Connection`](https://github.com/meh/rust-xkb/blob/672702869ce1c5c81d545ccbac859d516c41fea6/src/x11.rs#L55) again

So, basically everything expects an `xcb::Connection` only to then do `connection.get_raw_conn() as *mut _` with it. x11rb's `XCBConnection` can also provide the raw connection, but still cannot easily be used in these crates.

Are you interested in some shared crate for interoperability? I was thinking of a trait `AsRawXcbConnection` that can be used in the above cases instead of depending on `xcb::Connection` directly. Specifically:
```rust
#![allow(non_camel_case_types)]
pub enum xcb_connection_t {}

trait AsRawXcbConnection {
    fn as_raw_xcb_connection(&self) -> *mut xcb_connection_t;
}
```
This trait could then be implemented in xcb and x11rb and the above crates would work "with everything".

An alternative idea would be to implement something like this in an xkbcommon-binding-crate, but then the crate still only works with one version of xcb and one version of x11rb. The above idea has the benefit of making things version-independent (I think...).

I can publish such a crate and submit PRs to add support for it, but I would only do so if this has a chance of being merged in rust-xcb. Hence this issue to ask for opinions.

Thanks!

Edit: I now realise that the `trait` should be `unsafe` and require a valid `*mut xcb_connection_t` to be returned that is valid for as long as `&self`.

**Comment by rtbo** [comment]
Hi,
It's a good idea, I'm OK to add such implementation to rust-xcb and to use it in xkbcommon-rs.
