### ISSUE TITLE
Panicking: Misaligned pointer dereference when sending client message

### ISSUE THREAD

**Issue by cartoon-raccoon** [rust-x-bindings/rust-xcb#235]
My program panics with a misaligned pointer dereference error when I try to send an event.
I'm sending a ClientMessage event from the root window.

Attached is the rust backtrace of the panic, with irrelevant function calls removed:
[crashlog.txt](https://github.com/rust-x-bindings/rust-xcb/files/11962499/crashlog.txt)

And this is the relevant code that's calling the function:

```rust
let event = x::ClientMessageEvent::new(
    // cast! is just calling <<type> as XidNew>::new(id)
    cast!(x::Window, window),
    cast!(x::Atom, data.type_),
    to_send // client message data
);

Ok(self.conn.check_request(self.conn.send_request_checked(
    &x::SendEvent{
        propagate: false,
        destination: x::SendEventDest::Window(cast!(x::Window, window)),
        event_mask: x::EventMask::NO_EVENT,
        event: &event,
    }
))?)
```

I am aware that `cast!` is calling unsafe code, but I'm fairly sure that all values that it's dealing with already exist on the server.

**Comment by rtbo** [comment]
Have you tested with the main branch?
This was very likely fixed by #229

**Comment by cartoon-raccoon** [comment]
I'm using v1.2.1 from Crates.io. I'll do some further testing with the latest commit on the main branch to see if it's fixed.

**Comment by hydrobeam** [comment]
I was having a similar issue that was fixed by switching to the main branch. 

Is there going to be a new release to make the fix available?

**Comment by rtbo** [comment]
`v1.2.2` is published
