### ISSUE TITLE
Unclear requirements for XTest fake input

### ISSUE THREAD

**Issue by jjholt** [rust-x-bindings/rust-xcb#238]
I'm quoting the signature for XTest's `FakeInput` below.

From reading [examples](https://cgit.freedesktop.org/xcb/demo/tree/app/xte/xte.c), I gather that `type` is XCB_KEY_PRESS, XCB_BUTTON_PRESS, etc.
[Xproto](https://xcb.freedesktop.org/manual/xproto_8h_source.html) has definitions for those constants, which I assume is what is expected.

Issue #219 is an alternative, but I assume either creating constants or passing events directly would be a far better solution. Thoughts?

```rust
xcb::xtest::FakeInput {
    r#type: u8,
    detail: u8,
    time: u32,
    root: Window,
    root_x: i16,
    root_y: i16,
    deviceid: u8,
}
```

**Comment by RealKC** [comment]
Maybe xcb could export an API that looks like this?

```rs
impl FakeInput {
    pub fn for_event<E: base::Event>(detail: u8, time: u32, root: Window, root_x: i16, root_y: i16, deviceid: u8) -> Self {
        Self {
            r#type: E::NUMBER,
            detail,
            time,
            root,
            root_x,
            root_y,
            deviceid,
       }
    }
}
```

**Comment by jjholt** [comment]
Alternatively it's just a trait autoimplemented for most base events. The only issue is that `KeyReleaseEvent` is a type alias of `KeyPressEvent`. Something like:
```rust
trait EventNumber {
    fn event_number(&self) -> u8 where Self: xcb::BaseEvent {
        <Self as xcb::BaseEvent>::NUMBER as u8
    }
}
```

**Comment by rtbo** [comment]
> The only issue is that KeyReleaseEvent is a type alias of KeyPressEvent

Yes this would be a problem.
Adding definitions such as `xcb::x::KEY_PRESS` or `xcb::x::BUTTON_PRESS` is not a big headache and would probably help.

**Comment by jjholt** [comment]
I'm trying to understand the xml-to-rust pipeline so I can create these constants, and I figured why not test making `KeyPressEvent` and `KeyReleaseEvent` two different structs? Copy and pasted the xml definition, changed the name and number, and as far as I can tell everything works as expected.

What was the reasoning for making Release events always a type alias of Press? I'm completely out of my depth here, but is it not simpler to separate the two events? then the existent `event::NUMBER` is already the solution

**Comment by rtbo** [comment]
> What was the reasoning for making Release events always a type alias of Press?

In Xlib, the two events are the same type:
```c
typedef struct {
	int type;		/* KeyPress or KeyRelease */
        /* other fields */
} XKeyEvent;
typedef XKeyEvent XKeyPressedEvent;
typedef XKeyEvent XKeyReleasedEvent;
```
In the XCB  xml definition, we have something similar:
```xml
  <event name="KeyPress" number="2">
    <!-- fields -->
  </event>

  <eventcopy name="KeyRelease" number="3" ref="KeyPress" />
```
So it is quite natural that in Rust, the `eventcopy` element generates a typedef.
But there is nothing preventing the generation of a new type (exactly the same as `KeyPressEvent`).
Apart maybe Semver, because I don't really want to have version 2.
I'm not quite sure where is the boundary between minor and major version.
