### ISSUE TITLE
Please detach project from the "forked" repo

### ISSUE THREAD

**Issue by intgr** [rust-x-bindings/rust-xcb#268]
I found it initially confusing that this repository is marked as "forked from [mstewartgallus/rust-xcb](https://github.com/mstewartgallus/rust-xcb)"

Please detach the fork by submitting a request: https://support.github.com/request/fork

I think choosing "Detach a fork" and then "Extract" is the most appropriate operation for this case.

**Comment by rtbo** [comment]
Didn't know this was possible. Just filed a ticket.
