### ISSUE TITLE
Support of XEmbed extension

### ISSUE THREAD

**Issue by igor-petruk** [rust-x-bindings/rust-xcb#270]
Please add the support for XEmbed messages to rust-xcb

**Comment by igor-petruk** [comment]
Also if I understand correctly, meanwhile, if I wanted to use XEmbed I would have to implement it by implementing my own Request for the Xembed extensions like here for XInput: https://rust-x-bindings.github.io/rust-xcb/src/xcb/home/runner/work/rust-xcb/rust-xcb/target/debug/build/xcb-a998406220fb707b/out/xinput.rs.html#25126

Unless there is a safer way to send messages that are not natively supported by the library, please let me know if there are any

**Comment by rtbo** [comment]
From what I see [here](https://specifications.freedesktop.org/xembed-spec/xembed-spec-0.5.html#idm45495561951968) you could simply build a [ClientMessageEvent](https://docs.rs/xcb/latest/xcb/x/struct.ClientMessageEvent.html) and it with the [`SendEvent`](https://docs.rs/xcb/latest/xcb/x/struct.SendEvent.html) request.

**Comment by igor-petruk** [comment]
Thank you for the pointer! I did not realize it worked for X extensions, I
will try 👍
