### ISSUE TITLE
Use &[u8] instead of &str

### ISSUE THREAD

**Issue by eduardosm** [rust-x-bindings/rust-xcb#34]
On some requests, strings are not necessarily UTF-8 or ASCII, so we should not enforce fields of type `<list type="char">` to be `&str`.
For example, the X11 documentation says that atom names should be Latin-1: https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#requests:InternAtom

**Comment by rtbo** [comment]
closing in favor of #96
