### ISSUE TITLE
xcb_connection_t not Sync and Send?

### ISSUE THREAD

**Issue by pyfisch** [rust-x-bindings/rust-xcb#38]
I tried to write a [winit](/tomaka/winit) backed with XCB but the compiler immediately complained that `xcb_connection_t` is not Sync and Send. Winit places connections in an Arc and creates them with lazy_static. Is it correct that XCB does not allow multiple threads to access connections or is merely an oversight?

**Comment by rtbo** [comment]
Normally, it should allow them just fine. `thread` feature was introduce for this.
I also noticed that the `threaded_window` example does not build anymore.

**Comment by chrisduerr** [comment]
I had the same issue. Added `features = ["thread"]` and it worked.
