### ISSUE TITLE
Code generation computes pointer size for host platform, not target

### ISSUE THREAD

**Issue by SimonSapin** [rust-x-bindings/rust-xcb#42]
`rs_client.py` contains this line:
```py
    ptr_size = 8 if sys.maxsize > 2**32 else 4
```

This is probably incorrect when cross-compiling for example from a 64-bit platform to a 32-bit platform.

**Comment by rtbo** [comment]
TARGET is available from Cargo, and I can use this table: https://github.com/llvm-mirror/llvm/blob/master/lib/Support/Triple.cpp#L1167

**Comment by SimonSapin** [comment]
I’ve only noticed this line in passing and went “Uh, this looks weird”. I haven’t seen any actual bug around this.

That said, Servo only (indirectly) use rust-xcb on desktop Linux, which if I remember correctly we only test on 64-bit. So we wouldn’t notice that bug.

**Comment by rtbo** [comment]
`v1.0` do not have pointer size dependent code generation.

**Comment by rtbo** [comment]
[v1.0.0](https://crates.io/crates/xcb/1.0.0) is released.
