### ISSUE TITLE
ffi function xcb_xkb_get_names_value_list_unpack is not generated

### ISSUE THREAD

**Issue by Timidger** [rust-x-bindings/rust-xcb#51]
Looking at the python script, it doesn't generate any unpack functions? Or at least that variable is defined but never used. Is this an oversight?

**Comment by rtbo** [comment]
It's quite likely that not all functions are generated.
XKB in particular is very complex to handle.

**Comment by rtbo** [comment]
This is not needed anymore in `v1.0`.
The extensions are implemented in rust directly, no more bindings to C functions need to be generated.

**Comment by rtbo** [comment]
[v1.0.0](https://crates.io/crates/xcb/1.0.0) is released.
