### ISSUE TITLE
DisplayString macro

### ISSUE THREAD

**Issue by dhardy** [rust-x-bindings/rust-xcb#77]
I seem to need the [`DisplayString`](https://tronche.com/gui/x/xlib/display/display-macros.html#DisplayString) macro to "clone" a connection [in order to create a hidden window with its own event loop from an existing window].

I don't see this in rust-XCB; could it possibly be added?

Edit: sorry, that's from the XLib API, not XCB. But the question remains: can I "clone" a `Connection` (i.e. open a new one for the same display)?

**Comment by rtbo** [comment]
There is no `Clone` implementation for `Connection`. But is it really useful? `Connection` is `Send` and `Sync`, and does not need to be `mut` so you can use the same instance everywhere in your program.

**Comment by dhardy** [comment]
This was a long time ago... I'm just going to close the issue.
