### ISSUE TITLE
present extension fails to build

### ISSUE THREAD

**Issue by jneem** [rust-x-bindings/rust-xcb#81]
I get errors like
```
error[E0425]: cannot find function `xcb_present_redirect_notify_notifies_iterator` in this scope
   --> /home/jneeman/programming/rust-xcb/target/debug/build/xcb-13b7b78f8b3e7366/out/present.rs:806:13
    |
806 |             xcb_present_redirect_notify_notifies_iterator(self.ptr)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

and a few more. I can work around this by commenting out the `RedirectNotify` event in `xml/present.xml`. As far as I can tell from the [docs](https://cgit.freedesktop.org/xorg/proto/presentproto/tree/presentproto.txt), the RedirectNotify event doesn't even exist yet; it's proposed for a future revision.

**Comment by rtbo** [comment]
[v1.0.0](https://crates.io/crates/xcb/1.0.0) is released.
