### ISSUE TITLE
Errors get swallowed

### ISSUE THREAD

**Issue by jneem** [rust-x-bindings/rust-xcb#83]
When using the xcb C API (or the raw ffi API in this crate), errors caused by the non-"checked" variants of a function get reported asynchronously in the event loop. When using the wrapped API in this crate, they don't.

I've tracked this down to the `Drop` impl on `VoidCookie`, which discards the reply.

**Comment by rtbo** [comment]
This will be fixed in `v1.0` (currently beta)

**Comment by rtbo** [comment]
[v1.0.0](https://crates.io/crates/xcb/1.0.0) is released.
