### ISSUE TITLE
Support for newer RandR versions

### ISSUE THREAD

**Issue by queer** [rust-x-bindings/rust-xcb#90]
The [latest RandR version](https://gitlab.freedesktop.org/xorg/proto/xcbproto/-/blob/master/src/randr.xml#L30) is 1.6; it'd be nice to have support for the new things that come therein, such as [monitors](https://cgit.freedesktop.org/xorg/proto/randrproto/commit/?id=4109f29861a7066970a2afd079d0fc2c12828bcb). Would this change just involve updating the relevant file(s) and rerunning `cargo build`?

**Comment by rtbo** [comment]
The `v1.0` API (currently beta) is targeting XCB-1.14, which targets randr-1.6.

See: https://rust-x-bindings.github.io/rust-xcb/branches/v1.0-dev/xcb/randr/struct.MonitorInfo.html

**Comment by rtbo** [comment]
[v1.0.0](https://crates.io/crates/xcb/1.0.0) is released.

**Comment by queer** [comment]
Thanks :D
