### ISSUE TITLE
How to get X11 errors as events?

### ISSUE THREAD

**Issue by psychon** [rust-x-bindings/rust-xcb#97]
I just spent way too long trying to figure out why X11 errors are silently eaten. In the end, I needed to use `gdb` and set a breakpoint on `xcb_discard_reply`. That's how I found this:
```
impl<'a, T: Copy + CookieSeq> Drop for Cookie<'a, T> {
    fn drop(&mut self) {
        unsafe { xcb_discard_reply(self.conn.get_raw_conn(), self.cookie.sequence()) };
    }
}
```
Thanks to the above, all X11 errors from unchecked requests (e.g. `set_input_focus()` with a non-existing window) are silently ignored unless I explicitly `std::mem::forget()` the cookie. That's quite surprising and totally not what I was expecting.

**Comment by Lompik** [comment]
I added ```Drop``` on ```Cookie``` based on your suggestion ironically (https://github.com/rtbo/rust-xcb/issues/57#issuecomment-536166739).

**Comment by psychon** [comment]
Thanks for finding that. I totally do not remember that. :-)

Okay... Meh. This is all not a good fit for the libxcb API. At least `VoidCookie`s for unchecked requests do not need that (there it would only ignore X11 errors since there is nothing else to ignore). Checked requests and requests with a reply would cause a memory leak without the `xcb_discard_reply()`, as explained in #57...

Sadly, libxcb has no API for "discard the reply and treat any errors as events".

**Comment by Lompik** [comment]
Thanks for opening the issue though. 
My understanding of ```_unchecked``` and ```_checked``` was totally wrong until this issue came up. The difference is just two different way of dealing with errors with ```_checked``` meaning "in a blocking fashion".
I don't see an easy fix though.

**Comment by psychon** [comment]
> The difference is just two different way of dealing with errors with _checked meaning "in a blocking fashion".

Since I believe this explanation could be improved/extended:

- When an X11 error occurs with an unchecked request, you get the error as an X11 event from `xcb_wait_for_event()` or `xcb_poll_for_event()`.
  - For requests without a reply, there is not much more to say here, I think
    - I am not sure what happens when one calls `xcb_request_check()` anyway. It *might* be that this behaves similarly to what happens in the following point (checked requests with a reply)
  - For requests with a reply... uhm... I'm not quite sure. It might be that when you call the `*_reply()` function, you still get the error (if it was not already returned as an event)
- When an X11 error occurs with a checked request, you get the error when you check for the reply.
  - For requests without a reply, you have to explicitly call `xcb_request_check()`.
  - For requests with a reply, there is not much more to say here: The `*_reply()` function gives you the error.

Then there is the default:
- Requests without a reply default to unchecked and have a `foo_checked()` function for sending a checked request
- Requests with a reply default to checked and have a `foo_unchecked()` function for sending an unchecked request

The `*_reply()` and `xcb_check_request()` functions are blocking in that they read from the X11 server until they "find what they are looking for".

**Comment by rtbo** [comment]
[v1.0.0](https://crates.io/crates/xcb/1.0.0) is released.
